### ISSUE TITLE
encoding job: panic when using unreadable streams on source input

### ISSUE THREAD

**Issue by flavioribeiro** [snickers/snickers#140]
[gmf](https://github.com/3d0c/gmf) panics when ingesting a source input with unreadable streams. I could reproduce with https://vp.nyt.com/video/2016/11/21/44025_1_22pope-letter_wg_240p.mp4

```
panic: unable to initialize codec for stream '2', error:%!(EXTRA *errors.errorString=Unable to find codec by value '0')

goroutine 50 [running]:
panic(0x446d500, 0xc42059a170)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/3d0c/gmf.(*Stream).CodecCtx(0xc42047a2c0, 0x0)
	/Users/207112/golang/src/github.com/3d0c/gmf/stream.go:49 +0x301
github.com/snickers/snickers/encoders.processAllFramesAndUpdateJobProgress(0xc4204201b0, 0xc420420210, 0xc420420270, 0xc420180a70, 0x10, 0xc4200c5310, 0x45, 0xc4201987b0, 0x2a, 0xc420180530, ...)
	/Users/207112/golang/src/github.com/snickers/snickers/encoders/ffmpeg.go:115 +0x186
github.com/snickers/snickers/encoders.FFMPEGEncode(0x474dea0, 0xc4201c6720, 0x474e420, 0xc420081920, 0xc420180a70, 0x10, 0x0, 0x0)
	/Users/207112/golang/src/github.com/snickers/snickers/encoders/ffmpeg.go:51 +0x69e
github.com/snickers/snickers/pipeline.StartJob(0x474dea0, 0xc4201c6720, 0x474d780, 0xc4200920a8, 0x474e420, 0xc420081920, 0xc420180a70, 0x10, 0xc4200c5310, 0x45, ...)
	/Users/207112/golang/src/github.com/snickers/snickers/pipeline/pipeline.go:36 +0x653
created by github.com/snickers/snickers/server.(*SnickersServer).StartJob
	/Users/207112/golang/src/github.com/snickers/snickers/server/job_handlers.go:127 +0x4a6
exit status 2
```

**Comment by flavioribeiro** [comment]
refs https://github.com/3d0c/gmf/issues/49
